### ISSUE TITLE
goreleaser issues

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-go/mapcleaner#185]
## Target: `windows_amd64_v1`

* https://github.com/minetest-go/mapcleaner/actions/runs/7056592561/job/19208825845
```
gcc: error: unrecognized command-line option ‘-mthreads’; did you mean ‘-pthread’?
```

## Target: `linux_arm_6`

* https://github.com/minetest-go/mapcleaner/actions/runs/7056568517/job/19208764683
```
gcc: error: unrecognized command-line option '-marm'; did you mean '-mabm'?
```

**Comment by ronoaldo** [comment]
Once minetest-go/mtdb#80 gets merged the goreleaser should resume to work!
![Screenshot_20231202_011414](https://github.com/minetest-go/mapcleaner/assets/564649/c77a6dce-5ca5-4d30-acca-f8a799c501d0)
